<a href="https://colab.research.google.com/github/Robotmcgregor/earth-analytics-python-env/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.tensorflow.org/guide/tensor

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [1]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


## Creating Tensors

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [3]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [5]:
print(string)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


# Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

In [21]:
rank1_tensor =tf.Variable(["tensor1", "tensor2", "tensor3"], tf.string)

In [26]:
rank2_tensor = tf.Variable([["tensor1", "tensor2"],["tensor3", "tensor4"], ["tensor5", "tensor6"]], tf.string) #matricis

To determine the rank of a tensor we can call the following method.

In [31]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [28]:
rank2_tensor.shape

TensorShape([3, 2])

## Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [34]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
print(tensor3)
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [29]:
tensor1.shape

TensorShape([1, 2, 3])

In [30]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.


*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.